# Generated by Django 3.1 on 2020-09-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0002_auto_20200915_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price_product',
            field=models.CharField(max_length=20),
        ),
    ]
